# Generated by Django 4.0.3 on 2022-03-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('is_holiday', models.BooleanField(default=False, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=255)),
                ('description', models.TextField(default=None, max_length=65535, null=True)),
                ('reference', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('priority', models.IntegerField(choices=[(0, '☆☆☆'), (1, '★☆☆'), (2, '★★☆'), (3, '★★★')], default=0)),
                ('cost', models.IntegerField(default=0)),
                ('deadline', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
    ]
