# Generated by Django 4.0.3 on 2022-05-02 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('is_holiday', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255)),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=255)),
                ('description', models.TextField(blank=True, default=None, max_length=65535, null=True)),
                ('reference', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('milestone', models.BooleanField(default=False)),
                ('priority', models.IntegerField(choices=[(0, '☆☆☆'), (1, '★☆☆'), (2, '★★☆'), (3, '★★★')], default=0)),
                ('cost', models.IntegerField(default=0)),
                ('start', models.DateTimeField(blank=True, default=None, null=True)),
                ('deadline', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Todo'), (1, 'Doing'), (2, 'Done'), (4, 'Aborted')], default=0)),
                ('project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.project')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskPosition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_task', to='main.task')),
                ('pre', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pre_task', to='main.task')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField(default=0)),
                ('end', models.DateTimeField(default=0)),
                ('task', models.ForeignKey(blank=None, default=None, null=None, on_delete=django.db.models.deletion.CASCADE, to='main.task')),
            ],
        ),
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField(default=None, max_length=65535, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=None, default=None, null=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
