# Generated by Django 4.0.3 on 2022-03-29 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_calendar_is_holiday_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPosition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_task', to='main.task')),
                ('pre', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pre_task', to='main.task')),
            ],
        ),
    ]
