# Generated by Django 4.0.3 on 2022-03-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_taskposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
