# Generated by Django 4.0.3 on 2022-03-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_task_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='milestone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'Todo'), (1, 'Doing'), (2, 'Done'), (4, 'Aborted')], default=0),
        ),
    ]
