# Generated by Django 4.0.3 on 2022-04-03 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_task_assignee_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.BigIntegerField(default=0)),
                ('end', models.BigIntegerField(default=0)),
                ('task', models.ForeignKey(blank=None, default=None, null=None, on_delete=django.db.models.deletion.CASCADE, to='main.task')),
            ],
        ),
    ]
